version: '3.8'
services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=https://supabase-quiz.kerboul.me
    ports:
      - "3000:3000"

