services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Exposez le port de votre application
    environment:
      - NODE_ENV=production
      # Vous pouvez ajouter d'autres variables d'environnement si nécessaire
    restart: unless-stopped
