name: Deploy to production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  k6-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Start app in background
        run: npm run start &
        env:
          NODE_ENV: test
      - name: Wait for app to be ready
        run: |
          for i in {1..20}; do
            nc -z localhost 3000 && echo 'App is up!' && exit 0
            sleep 2
          done
          echo 'App did not start in time' && exit 1
      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6
      - name: Run k6 smoke tests
        run: k6 run k6_api_smoke.test.js

  deploy:
    needs: k6-smoke
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Configuration
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_GENERAL_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H kerboul.me >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Deploy to Production
        run: |
          echo "Exécution du script de déploiement via SSH..."
          ssh -i ~/.ssh/id_rsa root@kerboul.me "ssh quiz-server 'cd ~/build-deploy && ./deploy.sh'"
          echo "Déploiement terminé avec succès!"
      - name: Cleanup SSH keys
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa
